# Generated by Django 2.2.4 on 2020-03-03 20:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0006_auto_20200303_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='guid',
            field=models.UUIDField(default=uuid.uuid1, editable=False),
        ),
    ]
