# Generated by Django 2.2.4 on 2020-02-29 07:34

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(default=uuid.uuid1, editable=False)),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True, max_length=600)),
                ('url', models.URLField(max_length=300)),
                ('referring_url', models.URLField(blank=True, max_length=300)),
                ('other_referring_source', models.CharField(blank=True, max_length=200)),
                ('date_published', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('media_type', models.CharField(choices=[('VID', 'Video'), ('POD', 'Podcast'), ('PODEP', 'Podcast Episode'), ('TALK', 'Talk'), ('TUTOR', 'Tutorial'), ('COURSE', 'Course'), ('BOOK', 'Book'), ('BLOG', 'Blog'), ('GAME', 'Game'), ('EVENT', 'Event'), ('TOOL', 'Tool'), ('LIB', 'Library'), ('WEB', 'Website')], max_length=7)),
                ('paid', models.BooleanField(null=True)),
            ],
        ),
    ]
