# Generated by Django 2.2.4 on 2020-02-29 07:34

from django.conf import settings
from django.db import migrations, models
import resources.models
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resources', '0001_initial'),
        ('tagging', '__first__'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItems', to='tagging.CustomTag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='resource',
            name='user',
            field=models.ForeignKey(on_delete=models.SET(resources.models.get_sentinel_user), to=settings.AUTH_USER_MODEL),
        ),
    ]
