# Generated by Django 2.2.4 on 2019-09-06 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='resource_type',
            field=models.CharField(choices=[('tutorial', 'Tutorial'), ('course', 'Course'), ('community', 'Community')], max_length=255),
        ),
    ]
