# Generated by Django 2.2.4 on 2019-09-24 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='type',
        ),
        migrations.AddField(
            model_name='resource',
            name='media_type',
            field=models.CharField(choices=[('VID', 'Video'), ('POD', 'Podcast'), ('PODEP', 'Podcast Episode'), ('TALK', 'Talk'), ('TUTOR', 'Tutorial'), ('COURSE', 'Course'), ('BOOK', 'Book'), ('BLOG', 'Blog'), ('GAME', 'Game'), ('EVENT', 'Event'), ('TOOL', 'Tool'), ('LIB', 'Library'), ('WEB', 'Website')], default='WEB', max_length=7),
        ),
    ]
