# Generated by Django 2.2.4 on 2020-01-17 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_auto_20200116_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='description',
            field=models.TextField(blank=True, max_length=600),
        ),
    ]
