# Generated by Django 2.2.4 on 2020-01-11 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_auto_20190924_2157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='tags',
        ),
    ]
