# Generated by Django 2.2.4 on 2020-01-10 00:07

from django.conf import settings
from django.db import migrations, models
import resources.models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_auto_20200107_2214'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='referring_user',
            new_name='other_referring_source',
        ),
        migrations.AlterField(
            model_name='resource',
            name='user',
            field=models.ForeignKey(on_delete=models.SET(resources.models.get_sentinel_user), to=settings.AUTH_USER_MODEL),
        ),
    ]
