# Generated by Django 2.2.4 on 2020-01-18 18:36

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_auto_20200118_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.DeleteModel(
            name='TaggedResource',
        ),
    ]
