# Generated by Django 2.2.4 on 2020-01-10 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0005_auto_20200109_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='description',
            field=models.TextField(blank=True, max_length=600),
        ),
        migrations.AlterField(
            model_name='resource',
            name='other_referring_source',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='resource',
            name='referring_url',
            field=models.URLField(blank=True, max_length=600),
        ),
        migrations.AlterField(
            model_name='resource',
            name='url',
            field=models.URLField(max_length=600),
        ),
    ]
