# Generated by Django 2.2.4 on 2020-01-10 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0006_auto_20200109_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='description',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='resource',
            name='referring_url',
            field=models.URLField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='resource',
            name='url',
            field=models.URLField(max_length=300),
        ),
    ]
