# Generated by Django 2.2.4 on 2020-01-16 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0007_auto_20200110_1032'),
        ('resources', '0005_resource_tags'),
    ]

    operations = [
    ]
