# Generated by Django 2.2.4 on 2020-09-26 08:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import hangouts.models
import taggit.managers
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tagging', '0003_auto_20200508_1230'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resources', '0007_auto_20200303_1258'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hangout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(default=uuid.uuid1, editable=False)),
                ('status', models.CharField(blank=True, max_length=200)),
                ('hangout_type', models.CharField(choices=[('WATCH', 'Watch Me Code'), ('PRES', 'Presentation'), ('COWRK', 'Co-work with Me'), ('STUDY', 'Study Group'), ('PAIR', 'Pairing'), ('ACNT', 'Keep Me Accountable'), ('DISC', 'Discussion'), ('TEACH', 'I have something to teach')], max_length=6)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(allow_unicode=True, max_length=100, verbose_name='Slug')),
                ('short_description', models.TextField(max_length=300)),
                ('long_description', models.TextField(blank=True, max_length=600, null=True)),
                ('open_to_RSVP', models.BooleanField(default=False)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('recurring', models.BooleanField(default=False)),
                ('internal_platform', models.BooleanField(default=True)),
                ('external_platform_link', models.URLField(blank=True, max_length=300, null=True)),
                ('related_resources', models.ManyToManyField(blank=True, related_name='related_hangouts', to='resources.Resource')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='tagging.TaggedItems', to='tagging.CustomTag', verbose_name='Tags')),
                ('user', models.ForeignKey(on_delete=models.SET(hangouts.models.get_sentinel_user), to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HangoutSessions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(default=uuid.uuid1, editable=False)),
                ('status', models.CharField(blank=True, max_length=200)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('hangout_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_sessions', to='hangouts.Hangout')),
                ('related_resources', models.ManyToManyField(blank=True, related_name='related_hangout_sessions', to='resources.Resource')),
            ],
        ),
        migrations.CreateModel(
            name='HangoutResponses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(default=uuid.uuid1, editable=False)),
                ('express_interest', models.BooleanField(default=False)),
                ('request_to_join', models.BooleanField(default=False)),
                ('rsvp', models.BooleanField(default=False)),
                ('response_comment', models.TextField(blank=True, max_length=300, null=True)),
                ('status', models.TextField(max_length=10)),
                ('hangout_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_responses', to='hangouts.Hangout')),
                ('hangout_session_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_session_responses', to='hangouts.HangoutSessions')),
                ('user_id', models.ForeignKey(on_delete=models.SET(hangouts.models.get_sentinel_user), to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
