# Generated by Django 2.2.4 on 2020-05-08 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tagging', '0002_auto_20200405_0312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customtag',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=100, verbose_name='Slug'),
        ),
        migrations.AlterUniqueTogether(
            name='customtag',
            unique_together={('name', 'slug')},
        ),
    ]
