# Generated by Django 2.2.4 on 2020-04-07 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('tagging', '0002_auto_20200405_0312'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='taggeditems',
            unique_together={('content_type', 'object_id', 'tag')},
        ),
    ]
