name: Test

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    name: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run application
        run: docker-compose up -d web

      - name: Test Resources
        run: docker-compose run --rm manage test resources
        if: always()

      - name: Test Users
        run: docker-compose run --rm manage test users
        if: always()

      - name: Test UserAuth
        run: docker-compose run --rm manage test userauth
        if: always()

      - name: Check Migrations are up-to-date
        run: docker-compose run --rm manage makemigrations --check
        if: always()
